sites = ['Ireland', 'Italy', 'Egypt', 'Thailand', 'Hawaii']
print(sites)
print(sorted(sites))
print(sites)
print(sorted(sites, reverse=True))
print(sites)
sites.reverse()
print(sites)
sites.reverse()
print(sites)
sites.sort()
print(sites)
sites.sort(reverse=True)
print(sites)